## build runner
FROM node:alpine3.15

ENV NODE_VERSION 18.7.0

# Set directory
WORKDIR /app

# Move package.json
COPY package.json ./

# Install dependencies
RUN npm install && npm install nodemon -g

ENV PATH=/app/node_modules/.bin:$PATH

COPY . .

# Start bot
CMD [ "npm", "run", "dev" ]
