version: "3.7"

networks:
    jubileu-network:
        name: jubileu-network

services:
    lavalink:
        build:
            context: ../..
            dockerfile: docker/lavalink/Dockerfile.lavalink
        expose:
            - 2333
            - 2333/udp
        ports:
            - 2333:2333
        env_file: ../../.env
        networks:
            - jubileu-network
