services:
    lavalink:
        image: fredboat/lavalink:4.0.6
        container_name: lavalink
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        expose:
            - 2333
        ports:
            - 2333:2333
        env_file: .env
    app:
        container_name: app
        build:
            context: .
        env_file: .env
        depends_on:
            - lavalink