services:
    lavalink:
        image: fredboat/lavalink:4.0.8
        container_name: lavalink
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        expose:
            - 2333
        ports:
            - 2333:2333
        env_file: .env
        restart: always
    bot:
        container_name: bot
        build:
            context: .
            target: development
        volumes:
            - ./src:/usr/app/src
        env_file: .env
        environment:
            - LAVALINK_HOST=lavalink
        depends_on:
            - lavalink
        restart: always
        command: ["pnpm", "start:dev"]