version: '3.8'

services:
    lavalink:
        image: docker pull fredboat/lavalink:4.0.6-alpine
        container_name: lavalink
        restart: unless-stopped
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        expose:
            - 2333
        ports:
            - 2333:2333
    app:
        container_name: app
        env_file: .env
        restart: always
