services:
    lavalink:
        image: fredboat/lavalink:4.0.8
        container_name: lavalink
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        expose:
            - 2333
        ports:
            - 2333:2333
        env_file: .env
        restart: always
    bot:
        container_name: bot
        build:
            context: .
        env_file: .env
        depends_on:
            - lavalink
        restart: always