services:
    lavalink:
        image: fredboat/lavalink:4.1.1
        container_name: lavalink
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        expose:
            - 2333
        ports:
            - 2333:2333
        env_file: .env
        restart: always
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:2333/version', '-H', 'Authorization;']
            interval: 30s
            timeout: 1s
            retries: 5
            start_period: 30s
    bot:
        container_name: bot
        build:
            context: .
            target: development
        env_file: .env
        environment:
            - LAVALINK_HOST=lavalink
            - LAVALINK_PORT=2333
        depends_on:
            lavalink:
                condition: service_healthy
                restart: false
        restart: always
        command: ['pnpm', 'start:dev']
